services:
  backend:
    build:
      context: ./backend
    container_name: rend-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - rend-network

  frontend:
    build:
      context: ./frontend
    container_name: rend-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - rend-network

networks:
  rend-network:
    driver: bridge
