const mongoose = require("mongoose");

const agreementSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
    },
    type: {
      type: String,
      enum: ['lease', 'purchase', 'maintenance', 'termination', 'custom'],
      required: true,
    },
    property: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Property',
      required: function() {
        return this.type !== 'custom';
      },
    },
    parties: {
      landlord: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: function() {
          return ['lease', 'termination'].includes(this.type);
        },
      },
      tenant: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: function() {
          return ['lease', 'termination'].includes(this.type);
        },
      },
      buyer: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: function() {
          return this.type === 'purchase';
        },
      },
      seller: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: function() {
          return this.type === 'purchase';
        },
      },
      service_provider: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: function() {
          return this.type === 'maintenance';
        },
      },
      witnesses: [{
        name: String,
        email: String,
        phone: String,
        signature: String,
      }]
    },
    terms: {
      duration: String, // e.g., "12 months", "6 months"
      rentAmount: {
        type: Number,
        required: function() {
          return this.type === 'lease';
        },
      },
      securityDeposit: {
        type: Number,
        required: function() {
          return this.type === 'lease';
        },
      },
      purchasePrice: {
        type: Number,
        required: function() {
          return this.type === 'purchase';
        },
      },
      paymentSchedule: String,
      paymentMethod: {
        type: String,
        enum: ['Cash', 'Bank Transfer', 'Online Payment', 'Check', 'Installment'],
      },
      maintenanceResponsibilities: String,
      utilities: [String],
      restrictions: [String],
      terminationReason: String,
      noticePeriod: String,
      serviceDetails: {
        serviceType: String,
        frequency: String,
        cost: Number,
        nextServiceDate: Date,
      }
    },
    dates: {
      startDate: {
        type: Date,
        required: function() {
          return ['lease', 'purchase', 'maintenance'].includes(this.type);
        },
      },
      endDate: {
        type: Date,
        required: function() {
          return this.type === 'lease';
        },
      },
      signingDate: {
        type: Date,
        default: Date.now,
      },
      noticeDate: {
        type: Date,
        required: function() {
          return this.type === 'termination';
        },
      },
      effectiveDate: {
        type: Date,
        required: function() {
          return this.type === 'termination';
        },
      },
    },
    status: {
      type: String,
      enum: ['draft', 'pending', 'active', 'expired', 'terminated', 'completed'],
      default: 'draft',
    },
    documents: [{
      type: {
        type: String,
        enum: ['agreement', 'signature', 'receipt', 'certificate', 'other'],
        default: 'agreement',
      },
      name: String,
      url: String,
      uploadDate: {
        type: Date,
        default: Date.now,
      },
      size: Number,
      mimeType: String,
    }],
    signatures: [{
      party: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
      role: String, // landlord, tenant, buyer, seller, witness
      signature: String, // Base64 or URL
      signedAt: {
        type: Date,
        default: Date.now,
      },
      ipAddress: String,
    }],
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    isTemplate: {
      type: Boolean,
      default: false,
    },
    templateCategory: String,
    customClauses: [String],
    notes: String,
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    relatedTransaction: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Payment', // or other transaction models
    },
  },
  { timestamps: true }
);

const Agreement = mongoose.model("Agreement", agreementSchema);

module.exports = Agreement;
