const listings = [
  {
    id: 1,
    title: "Modern Apartment in Lazimpat",
    category: "rent",
    city: "Kathmandu",
    area: "Lazimpat",
    price: 45000,
    beds: 2,
    baths: 2,
    type: "Apartment",
    imageUrl:
      "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.8,
    isFeatured: true,
  },
  {
    id: 2,
    title: "Family Home in Bhaisepati",
    category: "buy",
    city: "Lalitpur",
    area: "Bhaisepati",
    price: 22500000,
    beds: 4,
    baths: 3,
    type: "House",
    imageUrl:
      "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.9,
    isFeatured: true,
  },
  {
    id: 3,
    title: "Serviced Room near Lakeside",
    category: "rent",
    city: "Pokhara",
    area: "Lakeside",
    price: 18000,
    beds: 1,
    baths: 1,
    type: "Room",
    imageUrl:
      "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.6,
    isFeatured: true,
  },
  {
    id: 4,
    title: "Commercial Space in New Baneshwor",
    category: "rent",
    city: "Kathmandu",
    area: "New Baneshwor",
    price: 120000,
    beds: 0,
    baths: 1,
    type: "Commercial",
    imageUrl:
      "https://images.pexels.com/photos/37347/office-freelancer-computer-business-37347.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: 5,
    title: "City View Apartment in Sitapaila",
    category: "buy",
    city: "Kathmandu",
    area: "Sitapaila",
    price: 13500000,
    beds: 3,
    baths: 2,
    type: "Apartment",
    imageUrl:
      "https://images.pexels.com/photos/4392270/pexels-photo-4392270.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: 6,
    title: "Budget Room in Koteshwor",
    category: "rent",
    city: "Kathmandu",
    area: "Koteshwor",
    price: 9000,
    beds: 1,
    baths: 1,
    type: "Room",
    imageUrl:
      "https://images.pexels.com/photos/4069297/pexels-photo-4069297.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.2,
    isFeatured: false,
  },
];

module.exports = { listings };

